# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: light.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='light.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0blight.proto\"\x1d\n\x0bLightStatus\x12\x0e\n\x06status\x18\x01 \x01(\x02\x32X\n\x05Light\x12&\n\x06turnOn\x12\x0c.LightStatus\x1a\x0c.LightStatus\"\x00\x12\'\n\x07turnOff\x12\x0c.LightStatus\x1a\x0c.LightStatus\"\x00\x62\x06proto3'
)




_LIGHTSTATUS = _descriptor.Descriptor(
  name='LightStatus',
  full_name='LightStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='LightStatus.status', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['LightStatus'] = _LIGHTSTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LightStatus = _reflection.GeneratedProtocolMessageType('LightStatus', (_message.Message,), {
  'DESCRIPTOR' : _LIGHTSTATUS,
  '__module__' : 'light_pb2'
  # @@protoc_insertion_point(class_scope:LightStatus)
  })
_sym_db.RegisterMessage(LightStatus)



_LIGHT = _descriptor.ServiceDescriptor(
  name='Light',
  full_name='Light',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=46,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='turnOn',
    full_name='Light.turnOn',
    index=0,
    containing_service=None,
    input_type=_LIGHTSTATUS,
    output_type=_LIGHTSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='turnOff',
    full_name='Light.turnOff',
    index=1,
    containing_service=None,
    input_type=_LIGHTSTATUS,
    output_type=_LIGHTSTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_LIGHT)

DESCRIPTOR.services_by_name['Light'] = _LIGHT

# @@protoc_insertion_point(module_scope)
