# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: smoke.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='smoke.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0bsmoke.proto\"\x1d\n\x0bSmokeStatus\x12\x0e\n\x06status\x18\x01 \x01(\x02\x32X\n\x05Smoke\x12&\n\x06turnOn\x12\x0c.SmokeStatus\x1a\x0c.SmokeStatus\"\x00\x12\'\n\x07turnOff\x12\x0c.SmokeStatus\x1a\x0c.SmokeStatus\"\x00\x62\x06proto3'
)




_SMOKESTATUS = _descriptor.Descriptor(
  name='SmokeStatus',
  full_name='SmokeStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='status', full_name='SmokeStatus.status', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=15,
  serialized_end=44,
)

DESCRIPTOR.message_types_by_name['SmokeStatus'] = _SMOKESTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SmokeStatus = _reflection.GeneratedProtocolMessageType('SmokeStatus', (_message.Message,), {
  'DESCRIPTOR' : _SMOKESTATUS,
  '__module__' : 'smoke_pb2'
  # @@protoc_insertion_point(class_scope:SmokeStatus)
  })
_sym_db.RegisterMessage(SmokeStatus)



_SMOKE = _descriptor.ServiceDescriptor(
  name='Smoke',
  full_name='Smoke',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=46,
  serialized_end=134,
  methods=[
  _descriptor.MethodDescriptor(
    name='turnOn',
    full_name='Smoke.turnOn',
    index=0,
    containing_service=None,
    input_type=_SMOKESTATUS,
    output_type=_SMOKESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='turnOff',
    full_name='Smoke.turnOff',
    index=1,
    containing_service=None,
    input_type=_SMOKESTATUS,
    output_type=_SMOKESTATUS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_SMOKE)

DESCRIPTOR.services_by_name['Smoke'] = _SMOKE

# @@protoc_insertion_point(module_scope)
